# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dumpsters', '0010_auto_20160702_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpster',
            name='type',
            field=models.CharField(
                choices=[('edible', 'Food'), ('non-edible', 'Other stuff'), ('both', 'Food & Other stuff'),
                         ('unknown', 'Unknown')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='name',
            field=models.CharField(default='Unnamed Dumpster', max_length=255, null=True),
        ),
    ]
